-- ============================================================
-- BARBEARIA ZN — DATABASE / SUPABASE
-- Production schema
-- ============================================================

create table if not exists public.appointments (
    id bigint generated by default as identity primary key,
    barber_name text not null,
    service_name text not null,
    service_price numeric(10,2) not null,
    appointment_date date not null,
    appointment_time time not null,
    client_name text not null,
    client_phone text not null,
    status text not null default 'confirmed',
    created_at timestamptz not null default now()
);

create unique index if not exists unique_barber_date_time
on public.appointments (barber_name, appointment_date, appointment_time)
where status = 'confirmed';

create table if not exists public.staff_profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    role text not null check (role in ('owner', 'barber')),
    barber_name text,
    created_at timestamptz not null default now()
);

alter table public.appointments enable row level security;
alter table public.staff_profiles enable row level security;

drop policy if exists "Public can view appointments" on public.appointments;
drop policy if exists "Public can create appointments" on public.appointments;
drop policy if exists "Staff can view appointments" on public.appointments;
drop policy if exists "Staff can update appointments" on public.appointments;
drop policy if exists "Staff can delete appointments" on public.appointments;

drop policy if exists "Users can read own profile" on public.staff_profiles;
drop policy if exists "Staff can read own profile" on public.staff_profiles;
drop policy if exists "Owner can read staff profiles" on public.staff_profiles;

-- Público pode criar agendamentos, mas não pode consultar a tabela.
create policy "Public can create appointments"
on public.appointments
for insert
to anon, authenticated
with check (true);

-- Dono vê tudo; barbeiro vê somente a própria agenda.
create policy "Staff can view appointments"
on public.appointments
for select
to authenticated
using (
    exists (
        select 1
        from public.staff_profiles me
        where me.id = auth.uid()
          and (
              me.role = 'owner'
              or (
                  me.role = 'barber'
                  and me.barber_name = appointments.barber_name
              )
          )
    )
);

-- Dono pode atualizar tudo; barbeiro somente a própria agenda.
create policy "Staff can update appointments"
on public.appointments
for update
to authenticated
using (
    exists (
        select 1
        from public.staff_profiles me
        where me.id = auth.uid()
          and (
              me.role = 'owner'
              or (
                  me.role = 'barber'
                  and me.barber_name = appointments.barber_name
              )
          )
    )
)
with check (
    exists (
        select 1
        from public.staff_profiles me
        where me.id = auth.uid()
          and (
              me.role = 'owner'
              or (
                  me.role = 'barber'
                  and me.barber_name = appointments.barber_name
              )
          )
    )
);

-- Exclusão definitiva somente para o dono.
create policy "Staff can delete appointments"
on public.appointments
for delete
to authenticated
using (
    exists (
        select 1
        from public.staff_profiles me
        where me.id = auth.uid()
          and me.role = 'owner'
    )
);

-- Cada usuário autenticado pode consultar somente o próprio perfil.
create policy "Users can read own profile"
on public.staff_profiles
for select
to authenticated
using (id = auth.uid());

-- RPC segura para o site público consultar somente horários ocupados.
create or replace function public.get_booked_times(
    p_barber_name text,
    p_appointment_date date
)
returns table (appointment_time text)
language sql
security definer
set search_path = public
as $$
    select left(a.appointment_time::text, 5)
    from public.appointments a
    where a.barber_name = p_barber_name
      and a.appointment_date = p_appointment_date
      and a.status = 'confirmed'
    order by a.appointment_time;
$$;

revoke execute on function public.get_booked_times(text, date) from public;
grant execute on function public.get_booked_times(text, date) to anon, authenticated;

-- ============================================================
-- STAFF USERS
-- ============================================================
-- Crie os usuários primeiro em Supabase Authentication.
-- Depois insira seus UUIDs nesta tabela.
--
-- insert into public.staff_profiles (id, full_name, role, barber_name)
-- values ('AUTH_USER_UUID', 'Nome do Dono', 'owner', null);
--
-- insert into public.staff_profiles (id, full_name, role, barber_name)
-- values ('AUTH_USER_UUID', 'Robson', 'barber', 'Robson');
--
-- insert into public.staff_profiles (id, full_name, role, barber_name)
-- values ('AUTH_USER_UUID', 'Samuel', 'barber', 'Samuel');
--
-- insert into public.staff_profiles (id, full_name, role, barber_name)
-- values ('AUTH_USER_UUID', 'Henrique', 'barber', 'Henrique');
